#!/usr/bin/env bash

KERNELVERSION=$1
BUILDDIR=$2
MODULESDIR="/lib/modules/${KERNELVERSION}/kernel/misc"
SIGNING_SCRIP="${BUILDDIR}/scripts/sign-file"
KEYPEM="${BUILDDIR}/certs/signing_key.pem"
KEYX509="${BUILDDIR}/certs/signing_key.x509"
PARTUUID="$(lsblk -no PARTUUID,MOUNTPOINT | grep -E " /$" | cut -d' ' -f1)"

unalias ls 2> /dev/null
vBoxVersion="$(ls -d /usr/src/vboxhost-* | cut -d'-' -f2)"
vBoxModules=("vboxdrv.ko" "vboxnetadp.ko" "vboxnetflt.ko" "vboxpci.ko")

exitWithError () {
    local COLOR='\033[0;31m'
    local NC='\033[0m'
    echo -e "${COLOR}$1${NC}"
    exit 2
}

printLine (){
    local COLOR='\033[1;32m'
    local NC='\033[0m'
    echo -e "${COLOR}==>    $1${NC}"
}


## REMOVE THIS CODE FROM HERE
if [[ -f $BUILDDIR/.config ]]; then
    printLine "Copying $BUILDDIR/.config -> /boot/config-${KERNELVERSION}"
    cp --remove-destination $BUILDDIR/.config /boot/config-${KERNELVERSION}
else
    exitWithError "File $BUILDDIR/.config not found"
fi

if [[ -f $BUILDDIR/System.map ]]; then
    printLine "Copying $BUILDDIR/System.map -> /boot/System.map"
    cp --remove-destination $BUILDDIR/System.map /boot/System.map
else
    exitWithError "File $BUILDDIR/System.map"
fi

if [[ -f $BUILDDIR/arch/x86_64/boot/bzImage ]]; then
    printLine "Copying $BUILDDIR/arch/x86_64/boot/bzImage -> /boot/vmlinuz-${KERNELVERSION}"
    cp --remove-destination $BUILDDIR/arch/x86_64/boot/bzImage /boot/vmlinuz-${KERNELVERSION}
else
    exitWithError "File $BUILDDIR/arch/x86_64/boot/bzImage"
fi


printLine "Creating initramfs-${KERNELVERSION}.img file"
mkinitcpio -k ${KERNELVERSION} -g /boot/initramfs-${KERNELVERSION}.img
if [[ $? -ne 0 ]]; then
    exitWithError "ERROR: mkinitcpio failed"
fi

if [[ ! -f /boot/loader/entries/${KERNELVERSION}.conf ]]; then
    printLine "Creating entry file"
    (
    cat <<EOF
title Arch Linux
linux /vmlinuz-${KERNELVERSION}
version ${KERNELVERSION}
initrd /intel-ucode.img
initrd /initramfs-${KERNELVERSION}.img
options rootfstype=ext4 root=PARTUUID=${PARTUUID} rw
EOF
    ) > /boot/loader/entries/${KERNELVERSION}.conf
fi

printLine "Uninstalling old version of vboxhost/${vBoxVersion}"
dkms uninstall vboxhost/${vBoxVersion} -k $KERNELVERSION
printLine "Removing old version of vboxhost/${vBoxVersion}"
dkms remove vboxhost/${vBoxVersion} -k $KERNELVERSION

printLine "Building new version of vboxhost/${vBoxVersion}"
dkms build vboxhost/${vBoxVersion} -k $KERNELVERSION

printLine "Installing new version of vboxhost/${vBoxVersion}"
dkms install vboxhost/${vBoxVersion} -k $KERNELVERSION
if [[ $? -ne 0 ]]; then
    exitWithError "ERROR: installing DKMS modules failed"
fi

if [[ ! -f $KEYPEM ]]; then
    exitWithError "ERROR: ${KEYPEM} doesn't exists"
fi
if [[ ! -f $KEYX509 ]]; then
    exitWithError "ERROR: ${$KEYX509} doesn't exists"
fi

for module in "${vBoxModules[@]}"; do
    if [[ -f ${MODULESDIR}/${module} ]]; then
        printLine "Signing module $module"
        $SIGNING_SCRIP sha1 $KEYPEM $KEYX509 ${MODULESDIR}/${module}
    else
        exitWithError "ERROR: ${MODULESDIR}/${module} doesn't exists"
    fi
done
