#!/usr/bin/env bash

# TODO: validate config file loaded by the user
# TODO: implement lspci -k, lsmod and other command in helpful fashion so that the user knows what modules must keep

THISSCRIPT="$0"
BUILDDIR=
SOURCEDIR=
configFound=1
export CHOST="x86_64-pc-linux-gnu"
export CFLAGS="-march=native -O2 -pipe -msse3"
export CXXFLAGS="${CFLAGS}"
RUNXCONFIG=0
GETKERNEL=0
cpuno=$(grep -Pc "processor\t:" /proc/cpuinfo)
# cpuno=$(($cpuno + 1))

vercomp() {
    # FROM https://stackoverflow.com/questions/4023830/how-compare-two-strings-in-dot-separated-version-format-in-bash
    # thanks Dennis Williamson
    if [[ $1 == "$2" ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

shouldRunOldConfig() {
    local currentVersion="$1"
    local oldVersion="$(grep -E "# Linux/x86 [45]\.[0-9]{1,2}\.[0-9]{1,2} Kernel Configuration" ${BUILDDIR}/.config | grep -Eo "[45]\.[0-9]{1,2}\.[0-9]{1,2}")"
    vercomp $currentVersion $oldVersion
    return $?
}

exitWithError() {
    local COLOR='\033[0;31m'
    local NC='\033[0m'
    echo -e >&2 "${COLOR}ERROR: $1${NC}"
    exit 2
}

printLine() {
    local COLOR='\033[1;32m'
    local NC='\033[0m'
    echo -e "${COLOR}==>    $1${NC}"
}

checkDirectory() {
    local dir=$1
    if [[ ${dir: -1} == "/" ]]; then
        local dir=${dir::${#dir}-1}
    fi

    if [[ ! -d $dir || ! -w $dir ]]; then
        exitWithError "Directory $dir doesn't exists or it's not writable"
    fi
    echo $dir
}

refineKernelName() {
    local ver="$1"
    local kernelPath="/boot/vmlinuz-${ver}-${KERNELNAME}"
    if [[ -f $kernelPath ]]; then
        printLine "A Kernel ${KERNELNAME} was found!. Do you want to Replace it or Increment it (r, i)"
        read answer

        if [[ $answer == "i" || $answer == "I" ]]; then
            local FILES="${kernelPath}*"
            for f in $FILES
            do
                trackversion=$(cut -d'-' -f4 <<<$f)
            done

            if [[ -z $trackversion ]]; then
                local trackversion=1
            else
                local trackversion=$(($trackversion + 1))
            fi

            KERNELNAME="${KERNELNAME}-${trackversion}"
        fi
    fi
}

usage() {
    cat >&2 <<EOF
    Usage: $THISSCRIPT [options]

    Options:
      --help                      : This output.
      --edit                      : Either or not to run GUI tool to modify config file.
      --download                  : Either or not to download the kernel sources.
      --build PATH                : Building directory. This directory is where hearder will be saved
                                    and the kernel will be built.
      --source PATH               : Source directory. This directory is where the kernel sources are
                                    saved.
      --name NAME                 : How you want to name this kernel.
      --file PATH                 : Path to a config file.
      --backup                    : Path to save config file
      --ondone                    : Path to script to execute after $THISSCRIPT
EOF
}

downloadKernel() {
    local html="$(wget --output-document - --quiet https://www.kernel.org/ | grep -A 1 "latest_link")"
    local kernelName="$(echo $html | grep -Eo "linux-[4-9]\.[0-9]+\.?[0-9]*\.tar\.xz")"

    local mayorVersion="$(echo $kernelName | cut -d'-' -f2 | cut -d'.' -f1)"
    local version="$(echo $kernelName | grep -Eo "linux-[4-9]\.[0-9]+\.[0-9]+")"
    local tarFile="/usr/src/${kernelName}"

    if [[ ! -f $tarFile ]]; then
        printLine "Downloading latest Linux Kernel: version found ${kernelName}"
        wget --https-only https://cdn.kernel.org/pub/linux/kernel/v${mayorVersion}.x/${kernelName} -O $tarFile
        if [[ $? -ne 0 ]]; then
            exitWithError "Downloading ${kernelName} failed"
        fi
    fi

    printLine "Untaring $tarFile"
    tar -xf $tarFile -C /usr/src --overwrite
    if [[ $? -ne 0 ]]; then
        exitWithError "Untaring $tarFile failed"
    fi

    SOURCEDIR="/usr/src/${version}"
}

modifyConfig() {
    ROOTFSTYPE="$(lsblk -o MOUNTPOINT,FSTYPE | grep -E "^/ " | awk '{print $2}')"
    ROOTUUID="$(lsblk -o MOUNTPOINT,PARTUUID | grep -E "^/ " | awk '{print $2}')"
    SWAPUUID="$(lsblk -o FSTYPE,PARTUUID | grep -E "^swap " | awk '{print $2}')"
    TXT="CONFIG_CMDLINE_BOOL=y\n"
    TXT="${TXT}CONFIG_CMDLINE=\"rootfstype=${ROOTFSTYPE} root=PARTUUID=${ROOTUUID} rw resume=PARTUUID=${SWAPUUID}\"\n"
    # TXT="${TXT}CONFIG_CMDLINE_OVERRIDE=y\n"
    # quiet
    sed -Ei "s/^#? ?CONFIG_CMDLINE_OVERRIDE(=[ynm]| is not set)//" ${BUILDDIR}/.config
    sed -Ei "s/^#? ?CONFIG_CMDLINE[ =].*//" ${BUILDDIR}/.config
    sed -Ei "s/^#? ?CONFIG_CMDLINE_BOOL(=[ynm]| is not set)/${TXT}/" ${BUILDDIR}/.config
    sed -Ei "s/^CONFIG_LOCALVERSION=\".*\"$/CONFIG_LOCALVERSION=\"-${KERNELNAME}\"/" ${BUILDDIR}/.config
}

if [[ $EUID -ne 0 ]]; then
    exitWithError "This script must be run as root"
fi

while [ $# -gt 0 ]; do
    case "$1" in
    "--help")
        usage
        exit 0
        ;;
    "--edit")
        shift
        RUNXCONFIG=1
        ;;
    "--download")
        shift
        GETKERNEL=1
        ;;
    "--build")
        shift
        printLine "Checking if $1 is a valid directory"
        BUILDDIR="$(checkDirectory "$1")"
        shift
        ;;
    "--ondone")
        shift
        ONDONE="$(readlink -f $1)"
        shift
        ;;
    "--backup")
        shift
        printLine "Checking if $1 is a valid directory"
        TOSAVECONFIG="$(checkDirectory "$1")"
        shift
        ;;
    "--source")
        shift
        printLine "Checking if $1 is a valid directory"
        SOURCEDIR="$(checkDirectory "$1")"
        shift
        ;;
    "--name")
        shift
        KERNELNAME="$1"
        shift
        ;;
    "--file")
        shift
        CONFIGFILE="$(readlink -f $1)"
        echo $CONFIGFILE
        shift
        ;;
    *)
        exitWithError "Unknown command-line option $1"
        ;;
    esac
done

if [[ $GETKERNEL -eq 1 ]]; then
    downloadKernel
fi

if [[ -z $SOURCEDIR ]]; then
    exitWithError "--source is undefined"
fi

if [[ ! -d $SOURCEDIR ]]; then
    exitWithError "$SOURCEDIR doesn't exist"
fi


if [[ -z $BUILDDIR ]]; then
    exitWithError "--build is undefined"
fi

cd $SOURCEDIR || exit 2
VERSION="$(make -s kernelversion 2> /dev/null)"

if [[ -n $KERNELNAME ]]; then
    refineKernelName ${VERSION}
else
    exitWithError "A name for the kernel is needed"
fi

KERNELVERSION="${VERSION}-${KERNELNAME}"
BUILDDIR="${BUILDDIR}/${KERNELVERSION}"

if [[ -d $BUILDDIR ]]; then
    printLine "make O=$BUILDDIR distclean"
    make -j $cpuno V=0 O=$BUILDDIR distclean 2>> ${BUILDDIR}/Error 1> /dev/null
else
    printLine "mkdir ${BUILDDIR}"
    mkdir ${BUILDDIR}
fi

if [[ -f $CONFIGFILE ]]; then
    printLine "Config file found: ${CONFIGFILE}"
    cp $CONFIGFILE ${BUILDDIR}/.config
else
    zcat --version > /dev/null 2>&1
    if [[ $? -eq 0 &&  -f /proc/config.gz ]]; then
        printLine "zcat /proc/config.gz > ${BUILDDIR}/.config"
        zcat /proc/config.gz > ${BUILDDIR}/.config
    # elif [[ -f /boot/config* ]]; then
    #     exitWithError "CODE ME, please! I beg you."
        # get the highest config file from all and then cat it to ${BUILDDIR}/.config"
    else
        exitWithError "We couldn't find a config file to use."
        configFound=0
    fi
fi

if [[ $configFound -eq 1 ]]; then
    shouldRunOldConfig $VERSION
    versionValidation=$?
    if [[ $versionValidation -eq 1 ]]; then
        whatToRun="olddefconfig"
    elif [[ $versionValidation -eq 2 ]]; then
        exitWithError "You are downgrading your kernel, this is not supported"
    else
        whatToRun=
    fi
    if [[ $RUNXCONFIG -eq 1 ]]; then
        whatToRun="${whatToRun} menuconfig"
    fi
else
    whatToRun="defconfig menuconfig"
fi

modifyConfig

whatToRun="${whatToRun} all"
printLine "make -j $cpuno V=0 O=${BUILDDIR} $whatToRun"
make -j $cpuno --silent V=0 O=${BUILDDIR} $whatToRun 2>> ${BUILDDIR}/Error
if [[ $? -ne 0 ]]; then
    exitWithError "This command \"make -j $cpuno V=0 O=${BUILDDIR} $whatToRun\" failed"
fi

if [[ -d $TOSAVECONFIG ]]; then
    printLine "Saving ${BUILDDIR}/.config to $TOSAVECONFIG/config-${KERNELVERSION}"
    cp --remove-destination ${BUILDDIR}/.config $TOSAVECONFIG/config-${KERNELVERSION}
fi

if [[ -d /usr/lib/modules/${KERNELVERSION} ]]; then
    printLine "Removing /usr/lib/modules/${KERNELVERSION} directory"
    rm -rf /usr/lib/modules/${KERNELVERSION}
fi

printLine "make -j $cpuno V=0 O=${BUILDDIR} modules_install headers_install"
make -j $cpuno V=0 O=${BUILDDIR} modules_install headers_install 2>> ${BUILDDIR}/Error 1> /dev/null
if [[ $? -ne 0 ]]; then
    exitWithError "This command \"make -j $cpuno V=0 O=${BUILDDIR} modules_install headers_install\" failed"
fi

if [[ -f $BUILDDIR/.config ]]; then
    printLine "Copying $BUILDDIR/.config -> /boot/config-${KERNELVERSION}"
    cp --remove-destination $BUILDDIR/.config /boot/config-${KERNELVERSION}
else
    exitWithError "File $BUILDDIR/.config not found"
fi

if [[ -f $BUILDDIR/System.map ]]; then
    printLine "Copying $BUILDDIR/System.map -> /boot/System.map"
    cp --remove-destination $BUILDDIR/System.map /boot/System.map
else
    exitWithError "File $BUILDDIR/System.map"
fi

if [[ -f $BUILDDIR/arch/x86_64/boot/bzImage ]]; then
    printLine "Copying $BUILDDIR/arch/x86_64/boot/bzImage -> /boot/vmlinuz-${KERNELVERSION}"
    cp --remove-destination $BUILDDIR/arch/x86_64/boot/bzImage /boot/vmlinuz-${KERNELVERSION}
else
    exitWithError "File $BUILDDIR/arch/x86_64/boot/bzImage"
fi

printLine "Creating initramfs-${KERNELVERSION}.img file"
mkinitcpio -k ${KERNELVERSION} -g /boot/initramfs-${KERNELVERSION}.img
if [[ $? -ne 0 ]]; then
    exitWithError "ERROR: mkinitcpio failed"
fi

printLine "Creating entry file"
(cat <<EOF
title Arch Linux
linux /vmlinuz-${KERNELVERSION}
version ${KERNELVERSION}
initrd /intel-ucode.img
initrd /initramfs-${KERNELVERSION}.img
EOF
) > /boot/loader/entries/${KERNELVERSION}.conf

if [[ -x ${ONDONE} ]]; then
    printLine "Calling ${ONDONE} ${KERNELVERSION} ${BUILDDIR}"
    ${ONDONE} ${KERNELVERSION} ${BUILDDIR}
    if [[ $? -ne 0 ]]; then
        exitWithError "This command \"${ONDONE} ${KERNELVERSION} ${BUILDDIR}\" failed"
    fi
fi

printLine "Kernel ${KERNELVERSION} was successfully installed"
printLine "Bye!"
exit 0
